config/routes.rb
Greatlakes::Application.routes.draw do
  root :to => 'screens#index'

match '/pgpba',:to=>'screens#index'
match '/businessanalyticsprogram',:to=>'screens#home'
match '/businessanalyticsprogram/group1',:to=>'screens#group1'
match '/businessanalyticsprogram/thanks',:to=>'screens#thanks'
match '/businessanalyticsprogram/group2',:to=>'screens#home'
match '/businessanalyticsprogram/group3',:to=>'screens#home'
match '/application',:to=>'certified_program_users#new'
match '/pdf_download_pgpba',:to=>'screens#pdf_download_pgpba'
match '/download_pdf_pgpba',:to=>'screens#download_pdf_pgpba'
match '/download_brchr_pgpba',:to=>'screens#download_brchr_pgpba'
match '/terms-of-use',:to=>'screens#terms'
match '/privacy-policy',:to=>'screens#privacy'
match '/marketing', :to=>'screens#marketing'
resources :certified_program_users

end

app/models/certified_program_user.rb
class CertifiedProgramUser < ActiveRecord::Base
  attr_accessible :age, :city, :course, :email,  :mobile, :name, :upload, :gender, :date_of_birth, :marital_status, 
   :father_name, :father_occupation, :mother_name, :mother_occupation, :Nationality, :mailing_address, 
   :landline, :pg_degree, :pg_discipline, :pg_college, :pg_university, :pg_year, :pg_cpga, :gr_degree, :gr_discipline,
     :gr_college, :gr_university, :gr_year, :gr_cpga, :hsc_degree, :hsc_discipline, 
     :hsc_college, :hsc_university, :hsc_year, :hsc_cpga, :sc_degree, :sc_discipline, :sc_college,
     :sc_university, :sc_year, :sc_cpga, :experience, :ctc, :organization_a, :designation_a, :nature_of_work_a,
     :from_a, :to_a, :organization_b, :designation_b, :nature_of_work_b, :from_b, :to_b, :academic_honor_a,
     :academic_honor_b, :extracuricular_a, :extracuricular_b, :others_a, :others_b, :payment_mode,
     :current_city, :applicant_name
     

     validates :name, presence: true
     validates :gender, presence: true
     validates :date_of_birth, presence: true
     validates :marital_status, presence: true
     validates :father_name, presence: true
     validates :mother_name, presence: true
     validates :mailing_address, presence: true
     validates :mobile, presence: true
     validates :email, presence: true
     validates :gr_degree, presence: true
     validates :gr_discipline, presence: true
     validates :gr_college, presence: true
     validates :gr_university, presence: true
     validates :gr_year, presence: true
     validates :gr_cpga, presence: true
     validates :hsc_degree, presence: true
     validates :hsc_discipline, presence: true
     validates :hsc_college, presence: true
     validates :hsc_university, presence: true
     validates :hsc_year, presence: true
     validates :hsc_cpga, presence: true
     validates :sc_degree, presence: true
     validates :sc_discipline, presence: true
     validates :sc_college, presence: true
     validates :sc_university, presence: true
     validates :sc_year, presence: true
     validates :sc_cpga, presence: true
     validates :current_city, presence: true
     validates :applicant_name, presence: true


     def upload=(incoming_file)
    self.applicant_photo_name = incoming_file.original_filename
    self.applicant_photo_type = incoming_file.content_type
    self.applicant_photo= incoming_file.read
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def create
    @application = Application.find params[:application_code]
    @errors = ContactUsForm.validate_fields(params, @application)
    @application.save_contact_us_form(params[:contact_us_form]) if @errors.blank?

    respond_to do |format|
      format.js #{render :json => {:status => 'success'}.to_json}
    end
  end
end

app/controllers/certified_program_users_controller.rb
class CertifiedProgramUsersController < ApplicationController

  def show_applicant_image   
    @certificateprogramusers = CertifiedProgramUser.find(params[:id])
    send_data @certificateprogramusers.applicant_photo, :type => @certificateprogramusers.applicant_photo_type, :disposition => 'inline'
    http_cache(@certificateprogramusers)
  end
	def index
		
     @request_url= request.referer

  end
  def download_pdf_pgpba
    path = "#{Rails.root}/public/pdf/Opportunities_in_Analytics-Great_Lakes.pdf"
    send_data File.read(path),:filename => "Opportunities in Analytics - Great Lakes.pdf",:type => "application/pdf" ,disposition: "attachment"
  end


	def new
		@certificateprogramuser = CertifiedProgramUser.new
	end

	def create
		@certificateprogramuser = CertifiedProgramUser.new(params[:certified_program_user])

          
		if @certificateprogramuser.save		 
		 flash[:success] = "Application Submitted Succesfully"		
			redirect_to root_url             
		else		  
		 flash[:error] = "Mandatory Fields should not be empty" 
			 render :new          
		end
	end
	def show
		@certificateprogramuser=CertifiedProgramUser.find(params[:id])
	end
	def show_details
		@certificateprogramuser=CertifiedProgramUser.all
	end
end

app/controllers/screens_controller.rb
class ScreensController < ApplicationController
	
	def index
		  @download_file= false
		if request.referer.present? && request.referer.include?('businessanalyticsprogram')
			@download_file = true
		else
			# well, the request is not coming from businessanalyticsprogram
		end
	end

	def thanks
		
	end

	def thanks1
		
	end

	def marketing
		
	end

	def landing_page
	end

	def pdf_download_pgpba
		path = "#{Rails.root}/public/pdf/Great-Lakes-PGPBA.pdf"
		send_data File.read(path),:filename => "Great-Lakes-PGPBA",:type => "application/pdf" ,disposition: "attachment"
	end

	def download_pdf_pgpba
		path = "#{Rails.root}/public/pdf/Careers_in_Analytics_Great_Lakes.pdf"
		send_data File.read(path),:filename => "Careers_in_Analytics_Great_Lakes.pdf",:type => "application/pdf" ,disposition: "attachment"
	end

	def download_brchr_pgpba
		path = "#{Rails.root}/public/pdf/Business Analytics Program - Great Lakes - Brochure.pdf"
		send_data File.read(path),:filename => " Business Analytics Program - Great Lakes.pdf",:type => "application/pdf" ,disposition: "attachment"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require 'open-uri'

  def render_url(url)
    open url do |f|
      f.read.html_safe   # remove the 'html_safe' if you're on Rails 2.x
    end
  end
end

app/helpers/certified_program_user_helper.rb
module CertifiedProgramUserHelper
end

app/helpers/screens_helper.rb
module ScreensHelper
end

app/views/certified_program_users/new.html.erb
<div style="padding:10px;border:#b7b0b0 1px solid; width:1000px; margin:0px auto;">
<%= simple_form_for @certificateprogramuser do |f| %>
<table class="table">
<tr><td><%= f.label :name, "Name*"%></td><td><%= f.text_field :name, :required => true%></td>
<td><%= f.label :upload, "Upload your photograph" %></td><td><%= f.file_field :upload%></td>
</tr>
<tr><td><%= f.label :gender, "Gender*"%></td><td><%= f.radio_button(:gender, "male") %>Male
<%= f.radio_button(:gender, "female") %>Female
</td></tr>
<tr><td><%= f.label :date_of_birth, "Date of Birth*" %>(dd/mm/yyyy)</td><td><%= f.text_field :date_of_birth %>
  </td><td><%= f.label :marital_status, "Marital Status*"%></td><td><%= f.radio_button(:marital_status, "Single") %>Single
<%= f.radio_button(:marital_status, "Married") %>Married
</td></tr>
<tr><td><%= f.label :father_name, "Father's Name*"%></td><td><%= f.text_field :father_name%></td><td><%= f.label :father_occupation, "Father's Occupation"%></td><td><%= f.text_field :father_occupation%></td></tr>
<tr><td><%= f.label :mother_name, "Mother's Name*"%></td><td><%= f.text_field :mother_name%></td><td><%= f.label :mother_occupation, "Mother's Occupation"%></td><td><%= f.text_field :mother_occupation%></td></tr>
<tr><td><%= f.label :Nationality, "Nationality"%></td><td><%= f.text_field :Nationality%></td><td></td><td></td></tr>
<tr><td><%= f.label :mailing_address, "Mailing Address*"%></td><td colspan="3"><%= f.text_field :mailing_address%></td><td></td><td></td></tr>
<tr><td><%= f.label :mobile, "Mobile*" %></td>
      <td><%= f.text_field :mobile%></td><td><%= f.label :landline, "Landline" %></td>
      <td><%= f.text_field :landline%></td></tr>
<tr><td><%= f.label :email, "E-mail Id*" %></td>
      <td><%= f.text_field :email%></td><td></td><td></td>
</table>
<table class="table"><h4>Academic Qualifications*</h4>
     <tr><th>  Qualification</th><th>Degree</th><th>Discipline#</th><th>School/ College</th><th>Board/ University</th><th>Year of Completion</th><th>%/ CGPA</th></tr>
<tr><td>Post-Graduation(If any)</td><td><%= f.text_field :pg_degree, :style=>"width:120px;"%></td><td><%= f.text_field :pg_discipline, :style=>"width:120px;"%></td><td><%= f.text_field :pg_college, :style=>"width:120px;"%></td><td><%= f.text_field :pg_university, :style=>"width:120px;"%></td><td><%= f.text_field :pg_year, :style=>"width:120px;"%></td><td><%= f.text_field :pg_cpga, :style=>"width:120px;"%></td></tr>
<tr><td>Graduation*</td><td><%= f.text_field :gr_degree, :style=>"width:120px;"%></td><td><%= f.text_field :gr_discipline, :style=>"width:120px;"%></td><td><%= f.text_field :gr_college, :style=>"width:120px;"%></td><td><%= f.text_field :gr_university, :style=>"width:120px;"%></td><td><%= f.text_field :gr_year, :style=>"width:120px;"%></td><td><%= f.text_field :gr_cpga, :style=>"width:120px;"%></td></tr>
<tr><td>Higher Secondary (XII)*</td><td><%= f.text_field :hsc_degree, :style=>"width:120px;"%></td><td><%= f.text_field :hsc_discipline, :style=>"width:120px;"%></td><td><%= f.text_field :hsc_college, :style=>"width:120px;"%></td><td><%= f.text_field :hsc_university, :style=>"width:120px;"%></td><td><%= f.text_field :hsc_year, :style=>"width:120px;"%></td><td><%= f.text_field :hsc_cpga, :style=>"width:120px;"%></td></tr>
<tr><td>Secondary (X)*</td><td><%= f.text_field :sc_degree, :style=>"width:120px;"%></td><td><%= f.text_field :sc_discipline, :style=>"width:120px;"%></td><td><%= f.text_field :sc_college, :style=>"width:120px;"%></td><td><%= f.text_field :sc_university, :style=>"width:120px;"%></td><td><%= f.text_field :sc_year, :style=>"width:120px;"%></td><td><%= f.text_field :sc_cpga, :style=>"width:120px;"%></td></tr>
<tr><td colspan="3"># Branch of Engineering/ Science/ Arts/ Commerce/ Other</td></tr>

</table>
<table>
</tr>
<tr><td>Total Work Experience</td><td><%= f.select(:experience, options_for_select([['select', 1], ['0-1 year'], ['1-3 year'], ['3-5 years'], ['>5 years']])) %>
</td></tr>
<tr><td>Current Annual Salary (CTC)</td><td><%= f.select(:ctc, options_for_select([['select', 1], ['0-1 lakh'], ['1-3 lakhs'], ['3-5 lakhs'], ['>5 lakhs']])) %>
</td></tr>
</table>
<table class="table"><h4>Work Experience Details</h4>
    <tr><td></td><td>Organization</td><td>Designation</td><td>Nature of Work</td><td>From(MM/YYYY)</td><td>To(MM/YYYY)</td></tr>
    <tr><td>a</td><td><%= f.text_field :organization_a, :style=>"width:150px;"%></td><td><%= f.text_field :designation_a, :style=>"width:150px;"%></td><td><%= f.text_field :nature_of_work_a, :style=>"width:150px;"%></td><td><div class="input-append date datepicker" data-date="12-02-2012" data-date-format="dd-mm-yyyy"><%= f.text_field :from_a , :style=>"width:100px;"%><span class="add-on"><i class="icon-th"></i></span>
  </div></td><td><div class="input-append date datepicker" data-date="12-02-2012" data-date-format="dd-mm-yyyy"><%= f.text_field :to_a , :style=>"width:100px;"%><span class="add-on"><i class="icon-th"></i></span>
  </div></td></tr>
    <tr><td>b</td><td><%= f.text_field :organization_b, :style=>"width:150px;"%></td><td><%= f.text_field :designation_b, :style=>"width:150px;"%></td><td><%= f.text_field :nature_of_work_b, :style=>"width:150px;"%></td><td><div class="input-append date datepicker" data-date="12-02-2012" data-date-format="dd-mm-yyyy"><%= f.text_field :from_b , :style=>"width:100px;"%><span class="add-on"><i class="icon-th"></i></span>
  </div></td><td><div class="input-append date datepicker" data-date="12-02-2012" data-date-format="dd-mm-yyyy"><%= f.text_field :to_b , :style=>"width:100px;"%><span class="add-on"><i class="icon-th"></i></span>
  </div></td></tr></table>
  <table class="table"><h4>Awards and Achievements</h4>
<tr><td>a</td><td>Academic Honors</td><td><%= f.text_field :academic_honor_a , :style=>"width:600px;"%></td></tr>
<tr><td></td><td></td><td><%= f.text_field :academic_honor_b , :style=>"width:600px;"%></td></tr>
<tr><td>b</td><td> Extracurricular</td><td><%= f.text_field :extracuricular_a , :style=>"width:600px;"%></td></tr>
<tr><td></td><td></td><td><%= f.text_field :extracuricular_b , :style=>"width:600px;"%></td></tr>
<tr><td>c</td><td>Others (Specify)</td><td><%= f.text_field :others_a , :style=>"width:600px;"%></td></tr>
<tr><td></td><td></td><td><%= f.text_field :others_b , :style=>"width:600px;"%></td></tr>
  </table>
   
 <table class="table"><h4>Declaration</h4>
      <h6>I certify that information provided in this application form is correct.</h6>
      <tr><td>Current City*</td><td colspan="2"><%= f.text_field :current_city%></td><td>Applicant Name*</td><td><%= f.text_field :applicant_name%></td></tr>

</table>
<table>
</tr>
<tr><td></td><td><%= f.submit "submit", class: "btn btn-large btn-primary" %>
</td></tr>
<tr><td>  *Mandatory fields</td></tr>
</table>
      <% end %><script type="text/javascript">
$('.datepicker').datepicker()</script></div>

app/views/certified_program_users/show.html.erb
<div style="float:left">
  <%= render 'shared/side_menu' %>
</div>

<br>
<div class="row">
  <div class="span12 offset3" style="min-height:530px;">
<div style="border:#b7b0b0 1px solid; width:1000px; margin:0px auto;padding:5px;">
<%= link_to "PRINT", '#',:class=>"print", onclick: "printpage()" %>
<table class="table">
  <tr><td colspan="2"><h2>Application For PGPBA</h2></td><td colspan="2"><%= image_tag url_for(:controller => 'certified_program_users',:action => 'show_applicant_image', :id => @certificateprogramusers.id), width: "150", height: "150", :style=>"float: right;"%></td></tr>
<tr><td><%= "Name" %></td><td><%= @certificateprogramusers.name%></td></tr>
<tr><td>Gender</td><td>
<%= @certificateprogramusers.gender %>
</td></tr>
<tr><td><%=  "Date of Birth" %></td><td><%= @certificateprogramusers.date_of_birth %>
  </td><td><%= "Marital Status"%></td><td><%= @certificateprogramusers.marital_status%>
</td></tr>
<tr><td> Father's Name </td><td><%= @certificateprogramusers.father_name%></td><td> Father's Occupation</td><td><%= @certificateprogramusers.father_occupation%></td></tr>
<tr><td> Mother's Name</td><td><%= @certificateprogramusers.mother_name%></td><td> Mother's Occupation </td><td><%= @certificateprogramusers.mother_occupation%></td></tr>
<tr><td><%= "Nationality"%></td><td><%= @certificateprogramusers.Nationality%></td><td></td><td></td></tr>
<tr><td><%= "Mailing Address" %></td><td colspan="3"><%= @certificateprogramusers.mailing_address%></td><td></td><td></td></tr>
<tr><td><%= "Mobile" %></td>
      <td><%= @certificateprogramusers.mobile%></td><td><%= "Landline" %></td>
      <td><%= @certificateprogramusers.landline%></td></tr>
<tr><td><%= " E-mail" %></td>
      <td><%= @certificateprogramusers.email%></td><td></td><td></td>
</table>
<table class="table"><h4>Academic Qualifications*</h4>
     <tr><th>  Qualification</th><th>Degree</th><th>Discipline#</th><th>School/ College</th><th>Board/ University</th><th>Passing Year</th><th>%/ CGPA</th></tr>
<tr><td>Post-Graduation(If any)</td><td><%= @certificateprogramusers.pg_degree%></td><td><%= @certificateprogramusers.pg_discipline %></td><td><%= @certificateprogramusers.pg_college%></td><td><%= @certificateprogramusers.pg_university %></td><td><%= @certificateprogramusers.pg_year%></td><td><%= @certificateprogramusers.pg_cpga %></td></tr>
<tr><td>Graduation*</td><td><%= @certificateprogramusers.gr_degree%></td><td><%= @certificateprogramusers.gr_discipline%></td><td><%= @certificateprogramusers.gr_college%></td><td><%= @certificateprogramusers.gr_university%></td><td><%= @certificateprogramusers.gr_year%></td><td><%= @certificateprogramusers.gr_cpga%></td></tr>
<tr><td>Higher Secondary (XII)*</td><td><%= @certificateprogramusers.hsc_degree%></td><td><%= @certificateprogramusers.hsc_discipline%></td><td><%= @certificateprogramusers.hsc_college%></td><td><%= @certificateprogramusers.hsc_university%></td><td><%= @certificateprogramusers.hsc_year%></td><td><%= @certificateprogramusers.hsc_cpga%></td></tr>
<tr><td>Secondary (X)*</td><td><%= @certificateprogramusers.sc_degree%></td><td><%= @certificateprogramusers.sc_discipline%></td><td><%= @certificateprogramusers.sc_college%></td><td><%= @certificateprogramusers.sc_university%></td><td><%= @certificateprogramusers.sc_year%></td><td><%= @certificateprogramusers.sc_cpga%></td></tr>
<tr><td colspan="3"># Branch of Engineering/ Science/ Arts/ Commerce/ Other</td></tr>

</table>
<table>
</tr>
<tr><td>Total Work Experience</td><td><%= @certificateprogramusers.experience%>
</td></tr>
<tr><td>Current Annual Salary (CTC)</td><td><%= @certificateprogramusers.ctc %>
</td></tr>
</table>
<table class="table"><h4>Work Experience Details</h4>
    <tr><td></td><td>Organization</td><td>Designation</td><td>Nature of Work</td><td>From(MM/YYYY)</td><td>To(MM/YYYY)</td></tr>
    <tr><td>a</td><td><%= @certificateprogramusers.organization_a%></td><td><%= @certificateprogramusers.designation_a%></td><td><%= @certificateprogramusers.nature_of_work_a%></td><td><%= @certificateprogramusers.from_a %></td><td><%= @certificateprogramusers.to_a %></td></tr>
    <tr><td>b</td><td><%= @certificateprogramusers.organization_b%></td><td><%= @certificateprogramusers.designation_b%></td><td><%= @certificateprogramusers.nature_of_work_b%></td><td><%= @certificateprogramusers.from_b %></td><td><%= @certificateprogramusers.to_b %></td></tr></table>
  <table class="table"><h4>Awards and Achievements</h4>
<tr><td>a</td><td>Academic Honors</td><td><%= @certificateprogramusers.academic_honor_a %></td></tr>
<tr><td></td><td></td><td><%= @certificateprogramusers.academic_honor_b %></td></tr>
<tr><td>b</td><td> Extracurricular</td><td><%= @certificateprogramusers.extracuricular_a %></td></tr>
<tr><td></td><td></td><td><%= @certificateprogramusers.extracuricular_b %></td></tr>
<tr><td>c</td><td>Others (Specify)</td><td><%= @certificateprogramusers.others_a%></td></tr>
<tr><td></td><td></td><td><%= @certificateprogramusers.others_b %></td></tr>
  </table>
    <table class="table"><h4>Please choose any one payment mode for application fee*</h4>
      <tr><td colspan="3"><%= @certificateprogramusers.payment_mode%>Online Transfer
</td><td></td><td>Note: Application Fee Rs 500/- only</td></tr>
</table>
 <table class="table"><h4>Declaration</h4>
      <h6>I certify that information provided in this application form is correct.</h6>
      <tr><td>Current City*</td><td colspan="2"><%= @certificateprogramusers.current_city%></td><td>Applicant Name*</td><td><%= @certificateprogramusers.applicant_name%></td></tr>

</table>
<table>
</tr>

</table>
      </div>



<SCRIPT TYPE="text/javascript">function printpage()
  {
  window.print()
  }
</SCRIPT>









   

app/views/certified_program_users/show.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Email</Data></Cell>
        <Cell><Data ss:Type="String">City</Data></Cell>
        <Cell><Data ss:Type="String">Age</Data></Cell>
         <Cell><Data ss:Type="String">Mobile</Data></Cell>
         <Cell><Data ss:Type="String">Course Name</Data></Cell>
      </Row>
<% CertifiedProgramUser.find(:all).each do |user|%>
      <Row>
        
        <Cell><Data ss:Type="String"><%= user.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.email %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.city %></Data></Cell>
        <Cell><Data ss:Type="integer"><%= user.age %></Data></Cell>
        <Cell><Data ss:Type="integer"><%= user.mobile %></Data></Cell>
         <Cell><Data ss:Type="string"><%= user.course %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/certified_program_users/show_details.html.erb
<div class="side_menu" style="float:left">
  <%= render 'shared/side_menu' %>
</div>

<br>
<div class="row">
  <div class="span12 offset3" style="min-height:530px;">
   <h3 align = "center">Certificate Program Users</h3>
       <table class="table table-condensed table-hover table table-striped tablesorter" id="myTable">
    <thead>
      <tr class="tab_head">
        <th >Name</th>
        <th >Email</th>
           <th >City</th>
        <th >Age</th>
           <th >Mobile</th>
   <th >Course Name</th>
       </tr>
    </thead>
    <tbody>
 
       <% @certificateprogramusers.each do |user|%>
       <tr>
  <td><a href="<%= certified_program_user_path(user)%>"><%= user.name %></a></td>
  <td><%= user.email %></td>
  <td><%= user.date_of_birth %></td>
  <td><%= user.gender %></td>
  <td><%= user.mobile %></td>
  <td>PGPBA</td>
        
      </tr>
<%end%>

    </tbody>
  </table>


</div>
</div>

</div>


</div>

<script>
$(document).ready(function() 
    { 
        $("#myTable").tablesorter(); 
    } 
); 
</script>  

app/views/layouts/_download_popup.html.erb
 <div id="downloadpopupmodal" class="modal2 hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" > 
<button type="button" data-dismiss="modal" aria-hidden="true" style="float: right;margin-right: 15px;"><a href="#" onclick="close_popup()">close</a></button>

  <div class="modal-header" style="border-bottom:0px;height:12px;">
   <h2>Business Analytics Program - Great Lakes Brochure</h2>
  </div>
  <div class="modal2-body" >
  	<div data-configid="9553473/6784816" style="width: 100%; height: 94%;" class="issuuembed"></div><script type="text/javascript" src="//e.issuu.com/embed.js" async="true"></script>
   <!-- <div data-configid="9553473/6726207" style="width: 100%; height: 94%;" class="issuuembed"></div><script type="text/javascript" src="//e.issuu.com/embed.js" async="true"></script> -->
</div>
</div>

app/views/layouts/_header.html.erb
  <div class="navbar">
            <div class="container-fluid">
             
            <div class="nav-collapse collapse navbar-responsive-collapse">
                        <div class="header-section">
        <div class="logo"><a href="http://www.greatlakes.edu.in" target="_blank">
        	        <%= image_tag('greatlakes_logo.jpg',:width=>"173", :height=>"78") %>
</a></div>
<table cellpadding="5" style="margin:20px;float:right;"><tr><td><a href="https://classroom.beaconlearning.in/login" target="_top"><%= image_tag("lock.png", :style=>"width:40px;height:40px;")%></a></td><td><h4><a href="https://classroom.beaconlearning.in/login" target="_top">Student Login</a></h4></td></tr></table>
      </div>
          </div>
        </div>
        
      </div> 

app/views/layouts/_privacy_popup.html.erb
 <div id="privacy" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="width:720px;"> 
<!-- <button type="button"  style="float: right;margin-right: 15px;"><a href="#" onclick="close_popup()">close</a></button> -->
<a title="Close" data-dismiss="modal" aria-hidden="true" class="fancybox-item fancybox-close" href="javascript:;"></a>

 <div  class="loading" style="width:655px;padding:40px;font:15px arial;line-height:22px;">
  <div class="policyinner">
    <h1>Privacy policy</h1>
    <br/>
    Great Lakes is committed to protecting your privacy. We will only use the information that we collect about you lawfully. <br/>
    <br/>
    The information we hold will be accurate and up to date. You can check the information that we hold about you by emailing us. If you find any inaccuracies we will delete or correct it promptly. <br/>
    <br/>
    The personal information which we hold will be held securely in accordance with our internal security policy and the law. </div>

</div>
</div>

app/views/layouts/_program_popup.html.erb
 <div id="programpopupmodal" class="modal2 hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" > 
<button type="button" data-dismiss="modal" aria-hidden="true" style="float: right;margin-right: 15px;"><a href="#" onclick="close_popup()">close</a></button>

  <div class="modal-header" style="border-bottom:0px;height:12px;">

  </div>
  <div class="modal2-body" style="background-image:url('/assets/infographic.jpg');background-size: 100% 85%;background-repeat:no-repeat;">
  	<a href="/application" style="float: right;
margin-top: 40%;margin-right:9%;
color: transparent;"> Apply online</a><br>
	<a href="/" style="float: right;margin-right: -12%;color: transparent;margin-top: 40.5%;"> Learn more about program</a>
</div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/screens/create.js.erb
<% if @errors.blank? %>
  window.location = "<%= @application.redirect_url  %>"
<% else %>
  var errors = replaceAll('<%= escape_javascript(@errors.to_json)%>', "&quot;", "'")
  var errors_json = eval('(' + errors + ')')
  show_errors(errors_json);
  function replaceAll(txt, replace, with_this) {
    return txt.replace(new RegExp(replace, 'g'),with_this);
  }
<% end %>